POST http://localhost:30996/update
Content-Type: application/json

{
  "zen": "Anything added dilutes everything else.",
  "hook_id": 64314058,
  "hook": {
    "type": "Repository",
    "id": 64314058,
    "name": "web",
    "active": true,
    "events": [
      "push"
    ],
    "config": {
      "content_type": "form",
      "insecure_ssl": "0",
      "url": "https://blog-deploy.sardinefish.com/update"
    },
    "updated_at": "2018-11-20T08:48:15Z",
    "created_at": "2018-11-20T08:48:15Z",
    "url": "https://api.github.com/repos/SardineFish/Sardine-Blog/hooks/64314058",
    "test_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/hooks/64314058/test",
    "ping_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/hooks/64314058/pings",
    "last_response": {
      "code": null,
      "status": "unused",
      "message": null
    }
  },
  "repository": {
    "id": 158357645,
    "node_id": "MDEwOlJlcG9zaXRvcnkxNTgzNTc2NDU=",
    "name": "Sardine-Blog",
    "full_name": "SardineFish/Sardine-Blog",
    "private": false,
    "owner": {
      "login": "SardineFish",
      "id": 12628979,
      "node_id": "MDQ6VXNlcjEyNjI4OTc5",
      "avatar_url": "https://avatars0.githubusercontent.com/u/12628979?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/SardineFish",
      "html_url": "https://github.com/SardineFish",
      "followers_url": "https://api.github.com/users/SardineFish/followers",
      "following_url": "https://api.github.com/users/SardineFish/following{/other_user}",
      "gists_url": "https://api.github.com/users/SardineFish/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/SardineFish/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SardineFish/subscriptions",
      "organizations_url": "https://api.github.com/users/SardineFish/orgs",
      "repos_url": "https://api.github.com/users/SardineFish/repos",
      "events_url": "https://api.github.com/users/SardineFish/events{/privacy}",
      "received_events_url": "https://api.github.com/users/SardineFish/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/SardineFish/Sardine-Blog",
    "description": "The repo of my PHP blog server. http://www.sardinefish.com/",
    "fork": false,
    "url": "https://api.github.com/repos/SardineFish/Sardine-Blog",
    "forks_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/forks",
    "keys_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/teams",
    "hooks_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/hooks",
    "issue_events_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/issues/events{/number}",
    "events_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/events",
    "assignees_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/assignees{/user}",
    "branches_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/branches{/branch}",
    "tags_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/tags",
    "blobs_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/languages",
    "stargazers_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/stargazers",
    "contributors_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/contributors",
    "subscribers_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/subscribers",
    "subscription_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/subscription",
    "commits_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/contents/{+path}",
    "compare_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/merges",
    "archive_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/downloads",
    "issues_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/issues{/number}",
    "pulls_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/labels{/name}",
    "releases_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/releases{/id}",
    "deployments_url": "https://api.github.com/repos/SardineFish/Sardine-Blog/deployments",
    "created_at": "2018-11-20T08:44:06Z",
    "updated_at": "2018-11-20T08:44:06Z",
    "pushed_at": "2018-11-20T08:44:07Z",
    "git_url": "git://github.com/SardineFish/Sardine-Blog.git",
    "ssh_url": "git@github.com:SardineFish/Sardine-Blog.git",
    "clone_url": "https://github.com/SardineFish/Sardine-Blog.git",
    "svn_url": "https://github.com/SardineFish/Sardine-Blog",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "SardineFish",
    "id": 12628979,
    "node_id": "MDQ6VXNlcjEyNjI4OTc5",
    "avatar_url": "https://avatars0.githubusercontent.com/u/12628979?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/SardineFish",
    "html_url": "https://github.com/SardineFish",
    "followers_url": "https://api.github.com/users/SardineFish/followers",
    "following_url": "https://api.github.com/users/SardineFish/following{/other_user}",
    "gists_url": "https://api.github.com/users/SardineFish/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/SardineFish/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/SardineFish/subscriptions",
    "organizations_url": "https://api.github.com/users/SardineFish/orgs",
    "repos_url": "https://api.github.com/users/SardineFish/repos",
    "events_url": "https://api.github.com/users/SardineFish/events{/privacy}",
    "received_events_url": "https://api.github.com/users/SardineFish/received_events",
    "type": "User",
    "site_admin": false
  }
}


