POST http://localhost:30996/update
Content-Type: application/json
User-Agent: GitHub-Hookshot/0c1bc40
X-GitHub-Delivery: 8b14564e-ed39-11e8-98b7-6fa18e4b37ee
X-GitHub-Event: push
X-Hub-Signature: sha1=5437334b2edbf0f9b4b148c5f29f2907e2689459

< ./payload.json